name: acs
channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - numpy
  - pytorch
  - tqdm
  - pip:
    - transformers
    - accelerate
    - hydra-core
    - sentencepiece
    - simctg
    - mauve-text
